### ISSUE TITLE
Comparison with modular-bitfield

### ISSUE THREAD

**Issue by hecatia-elegua** [danlehmann/bitfield#4]
https://crates.io/crates/modular_bitfield is an older take on this idea and I planned to extend it or otherwise "build my own", though now I have found your lib and the "frontend" pretty much aligns with what I had in mind (coming closer to [a real arbitrary bitwidth integer rfc](https://internals.rust-lang.org/t/pre-rfc-arbitrary-bit-width-integers/15603)).

The question now is how these two differ.
Your code seems much more readable and up-to-date, though maybe it should also have some kind of benchmark against handwritten code akin to modular-bitfield? Anything else, other than cosmetics?

**Comment by danlehmann** [comment]
Hello and sorry the late response. I took a quick look at others before starting this project; I couldn't find what I was looking for a variety of reasons (though I am not sure which of those apply to modular-bitfield in particular):
- The use of byte arrays in some crates instead of simple types (e.g. u32) caused less efficient code generation,
- The use of a too-foreign looking macro language confused my IDE of choice (Clion).

bitbybit simply operates on a standard type like u32 or u64, doing shifts and masks. The "smarts" of the macro are all in #[], that my IDE ignores anyway. So no red underlines there.

I also wanted to make arbitrary-int's (similar to ux, but using generics) are core part of the library. If a field is u4, you shouldn't be able to pass in 24, for example. As a result, bitbybit has very little error checking, as most things are handled by the type system (or arbitrary-int in e.g. u4::new()).

I can do some benchmarks, shouldn't be too hard. The reason I didn't do that is simply as the code is essentially what I'd write manually anyway, so it seemed rather unnecessary. But confirming sounds like a good idea.

Let me know if this answers your questions :)

**Comment by hecatia-elegua** [comment]
Thank you, yes it does :)

Interesting that it started with IDE macro support issues. Will see how I can extend this for my needs.

**Comment by danlehmann** [comment]
Let's close this task? I don't think there's anything actionable in here any longer :)
